name: Verifica feature
description: "Crea una issue per la verifica di una feature aggiunta (Ruolo Verificatore)"
title: "[PoC]"
labels: ["enhancement", "task-verificatore"]
projects: ["GlitchHub-Team/2"]
type: feature
body:
- type: textarea
  id: description
  attributes:
    label: Descrizione della feature
