{
 "title": "NATS - Minimal",
 "tags": [
  "nats",
  "poc"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Connessioni attive",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({job=\"nats\",__name__=~\"(gnatsd|nats)_varz_connections\"})",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Messaggi / s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate({job=\"nats\",__name__=~\"(gnatsd|nats)_varz_in_msgs\"}[1m]))",
     "legendFormat": "in_msgs/s"
    },
    {
     "expr": "sum(rate({job=\"nats\",__name__=~\"(gnatsd|nats)_varz_out_msgs\"}[1m]))",
     "legendFormat": "out_msgs/s"
    }
   ]
  },
  {
   "title": "Bytes / s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate({job=\"nats\",__name__=~\"(gnatsd|nats)_varz_in_bytes\"}[1m]))",
     "legendFormat": "in_bytes/s"
    },
    {
     "expr": "sum(rate({job=\"nats\",__name__=~\"(gnatsd|nats)_varz_out_bytes\"}[1m]))",
     "legendFormat": "out_bytes/s"
    }
   ]
  }
 ]
}